# Generated by Django 3.2.10 on 2021-12-20 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflogin',
            name='staff',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_stafflogin', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
    ]
